hosts/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
    url("^$", views.host_mgr, name="hosts"),
    url("^hosts_index/$", views.hosts_index, name="hosts_index"),
    url("^host_mgr/$", views.host_mgr, name="host_mgr"),
    url("^hosts_list/$", views.hosts_list, name="hosts_list"),
    url("^file_upload/$", views.file_upload, name="file_upload"),
    url(r'^upload_script/$', views.uploadify_script),
    url(r'^handle_uploaded_file/$', views.handle_uploaded_file),
    url(r'^upload_list/$', views.upload_list),
    url(r'^file_del/$', views.file_del),
    url(r'^file_send/$', views.file_send),
    url(r'^file_push/$', views.file_push),
    url(r'^file_manage', views.file_manage,name='file_manage'),
    url("^multi_cmd/$", views.multi_cmd, name="multi_cmd"),
    url("^submit_task/$", views.submit_task, name="submit_task"),
    url("^command/$", views.command, name="command"),

]

myops/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from hosts import urls as hosts_urls
from applications import urls as apps_urls
from monitor import urls as monitor_urls
from hosts import views
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index,name='dashboard'),
    url(r'^hosts/', include(hosts_urls)),
    url(r'^apps/', include(apps_urls)),
    url(r'^monitor/', include(monitor_urls)),

    url("^assets/$", views.assets_index, name="assets"),
    #url("^monitor/$", views.monitor_index, name="monitor"),
    url("^login/$", views.acc_login, name="login"),
    url("^logout/$", views.acc_logout, name="logout")

]

hosts/models.py
#_*_coding:utf-8_*_

from django.db import models

# Create your models here.
from myauth import UserProfile

class Host(models.Model):
    hostname = models.CharField(max_length=64)
    ip_addr = models.GenericIPAddressField(unique=True)
    port = models.IntegerField(default=22)
    idc = models.ForeignKey('IDC')
    system_type_choices= (
        ('linux(vm)','Linux(VM)'),
        ('linux(p)','Linux(P)'),
    )
    system_type = models.CharField(choices=system_type_choices,max_length=32,default='linux')
    enabled = models.BooleanField(default=True)
    memo = models.TextField(blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return  "%s(%s)" %(self.hostname,self.ip_addr)
    class Meta:
        verbose_name = u'主机列表'
        verbose_name_plural = u"主机列表"
class IDC(models.Model):
    name = models.CharField(unique=True,max_length=64)
    memo = models.TextField(blank=True,null=True)

    def __unicode__(self):
        return  self.name

class HostUser(models.Model):
    auth_type_choices = (
        ('ssh-password', 'SSH/PASSWORD'),
        ('ssh-key', 'SSH/KEY'),
    )
    auth_type = models.CharField(choices=auth_type_choices,max_length=32,default='ssh-password')
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=128,blank=True,null=True)

    def __unicode__(self):
        return "(%s)%s" %(self.auth_type,self.username)

    class Meta:
        unique_together = ('auth_type','username','password')
        verbose_name = u'远程主机用户'
        verbose_name_plural = u"远程主机用户"
class HostGroup(models.Model):
    name = models.CharField(unique=True,max_length=64)
    memo = models.TextField(blank=True,null=True)

    def __unicode__(self):
        return  self.name
    class Meta:
        verbose_name = u'主机组'
        verbose_name_plural = u"主机组"
class BindHostToUser(models.Model):
    host = models.ForeignKey("Host")
    host_user= models.ForeignKey("HostUser")
    #host_user= models.ManyToManyField("HostUser")
    host_groups = models.ManyToManyField("HostGroup")

    class Meta:
        unique_together = ('host','host_user')
        verbose_name = u'主机与用户绑定关系'
        verbose_name_plural = u"主机与用户绑定关系"
    def __unicode__(self):
        return  '%s:%s' %(self.host.hostname, self.host_user.username)


    def get_groups(self):

        return ','.join([g.name for g in self.host_groups.select_related()])

class middleware(models.Model):
    name = models.CharField(verbose_name = "中间件名", max_length=50,null=True,blank=True)
    version = models.CharField(verbose_name = "中间件版本", max_length=50,null=True,blank=True)
    class Meta:
        managed =True
        verbose_name = "中间件"
        verbose_name_plural = "中间件"
    def __unicode__(self):
        return self.name

class app_user(models.Model):
    username = models.CharField(verbose_name = "用户名", max_length=20)
    password = models.CharField(verbose_name = "密码", max_length=20)
    middleware = models.ManyToManyField('middleware')
    class Meta:
        managed =True
        verbose_name = "中间件用户"
        verbose_name_plural = "中间件用户"
    
    def __unicode__(self):
        return self.username

    def get_middleware(self):
        return ','.join([g.name for g in self.middleware.select_related()])

class Subsys(models.Model):
    name = models.CharField(max_length=64)
    memo = models.TextField(blank=True,null=True)
    host = models.ManyToManyField('Host')


    def __unicode__(self):
        return  self.name


    class Meta:

        verbose_name = u'子系统'

        verbose_name_plural = u"子系统"
     
    def get_host(self):                                                                                                                 
        return ','.join([g.ip_addr for g in self.host.select_related()])

class App_host(models.Model):
    app_id = models.IntegerField(default=11)
    host_id = models.IntegerField(default=11)

class weblogic_admin_serverhost(models.Model):
    weblogic_admin_id = models.IntegerField(default=11)
    weblogic_server_id = models.IntegerField(default=11)

class App(models.Model):
    name = models.CharField(unique=True,max_length=64)
    package = models.CharField(max_length=30,null=True,blank=True)
    path = models.CharField(max_length=30,null=True,blank=True)
    memo = models.TextField(blank=True,null=True)
    subsys = models.ForeignKey(Subsys)
    host = models.ManyToManyField(Host)
    
    def __unicode__(self):
    
        return  self.name
    
    
    class Meta:
    
        verbose_name = u'应用'
    
        verbose_name_plural = u"应用"
    
    def get_subsys(self):
       return self.subsys.name
    
    #def get_host(self):
    #    return ','.join([g.ip_addr for g in self.host.select_related()])

class weblogic_admin(models.Model):
    primary = models.ForeignKey(Host)
    middleware = models.ForeignKey(middleware)
    username = models.ForeignKey(app_user)
    console_port = models.IntegerField(verbose_name = "控制台端口", null=True,blank=True)
    cluster = models.CharField(verbose_name = "集群名",max_length=30,null=True,blank=True)
    create_date = models.DateTimeField(verbose_name = "安装时间", null=True,blank=True)
    name = models.CharField(verbose_name = "系统名称", null=True,max_length=200,blank=True)
    servername = models.CharField(verbose_name = "实例名", default="AdminServer",null=True,max_length=200,blank=True)
    server_status = models.CharField(verbose_name = "状态", max_length=20,null=True,blank=True)
    admin_status = models.CharField(verbose_name = "状态", max_length=20,null=True,blank=True)
    date = models.DateTimeField(verbose_name = "修改时间", null=True,blank=True)
    serverhost = models.ManyToManyField('weblogic_server')

    def __unicode__(self):
        return  self.name
    
    class Meta:
        managed = True
        verbose_name = "weblogic控制台部署信息"
        verbose_name_plural = "weblogic控制台部署信息"

    def get_host(self):                                                                                                             
        return ','.join([g.managed_server_id.ip_addr for g in self.serverhost.select_related()])

class weblogic_server(models.Model):
        managed_server_id = models.ForeignKey(Host)
        #type = models.ForeignKey(middleware)
        apps_id = models.ForeignKey(App)
        server_name = models.CharField(verbose_name = "实例名", max_length=50,null=True,blank=True)
        server_port = models.IntegerField(verbose_name = "实例端口", null=True,blank=True)
        server_status = models.CharField(verbose_name = "状态", max_length=20,null=True,blank=True)
        date = models.DateTimeField(verbose_name = "修改时间", null=True,blank=True)
        def __unicode__(self):
            return  self.server_name


        class Meta:
        	managed = True
        	verbose_name = "weblogic实例部署信息"
        	verbose_name_plural = "weblogic实例部署信息"
        
        def get_app(self):
            return self.apps_id.name
        

        def get_managed_server(self):
            return self.managed_server_id.ip_addr

class java_test(models.Model):
      server_name = models.CharField(verbose_name = "工程名", max_length=50,null=True,blank=True)
      #app = models.ForeignKey(App)
      def __unicode__(self):
            return  self.server_name

class fuck(models.Model):
      name = models.CharField(verbose_name = "工程名", max_length=50,null=True,blank=True)
      #app = models.ForeignKey(App)
      def __unicode__(self):
            return  self.server_name

class java_process(models.Model):
      name = models.CharField(verbose_name = "名称",max_length=50,null=True,blank=True)
      pid = models.IntegerField(verbose_name = "进程ID", null=True,blank=True)
      path = models.CharField(verbose_name = "部署路径", max_length=50,null=True,blank=True)
      port = models.IntegerField(verbose_name = "端口", null=True,blank=True)
      host = models.ForeignKey(Host)
      cpu = models.CharField(verbose_name = "cpu", max_length=50,null=True,blank=True)
      date = models.DateTimeField(verbose_name = "时间", null=True,blank=True)
      status = models.CharField(verbose_name = "状态", max_length=50,null=True,blank=True)
      
      def __unicode__(self):
            return  self.name
      class Meta:
        managed = True
        verbose_name = "java部署信息"
        verbose_name_plural = "java部署信息"

class java_server(models.Model):
       name = models.CharField(verbose_name = "名称", max_length=50,null=True,blank=True)
       app = models.ForeignKey(App)      
       process = models.ManyToManyField(java_process)
       status = models.CharField(verbose_name = "状态", max_length=50,null=True,blank=True)
       def __unicode__(self):
            return  self.name

       class Meta:
        managed = True
        verbose_name = "java后台进程"
        verbose_name_plural = "java后台进程"

       def get_subsys(self):                                                                                           
            return self.app.subsys.name

       def get_process_ip(self):
            return ','.join([g.host.ip_addr for g in self.process.select_related()])
       def get_process_path(self):
            return ','.join([g.path for g in self.process.select_related()])

class web_server(models.Model):
      name = models.CharField(verbose_name = "实例名", max_length=50,null=True,blank=True)
      type = models.ForeignKey(middleware)
      project = models.CharField(verbose_name = "部署单元",max_length=50,null=True,blank=True)
      path = models.CharField(verbose_name = "部署路径",max_length=50,null=True,blank=True)
      host = models.ForeignKey(Host)
      date = models.DateTimeField(verbose_name = "时间", null=True,blank=True)
      status = models.CharField(verbose_name = "状态", max_length=50,null=True,blank=True)

class zk_server(models.Model):
      name = models.CharField(verbose_name = "实例名", max_length=50,null=True,blank=True)
      type = models.ForeignKey(middleware)

templates/hosts/cmd_mgr.html
{% extends "hosts/dashboard.html" %}
{% block content-panel  %}
{% load staticfiles %}
<link href="{% static 'css/fileinput.min.css' %}" rel="stylesheet" type="text/css">
<script type="text/javascript" src="{% static 'js/fileinput.min.js' %} "> </script>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Host Info</h2>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        <div class="panel panel-default">
        <div class="panel-heading"></div>
        <div class="panel-body">
                <div class="demo-box">
                        <div id="id_span_msg"></div>
                       <textarea name="cmd" class="form-control" rows="3" placeholder="输入要执行的命令..."></textarea>
                </div>
        <div id="id_span_msg">{{ sub.Succeed }}</div>
        <div id="result">{{ result.cmd }}</div>
        </div>
        </div>
        <!-- /.row -->
        <!-- <table id="tb_departments"></table>
        <label class="control-label" >常用:</label>
        <span class="label label-default">查看机器负载</span>
        <span class="label label-default">磁盘使用率</span>
        <span class="label label-default">TOP10进程</span>
        -->
        <div >
         <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group" >
                    <label class="control-label " for="group_id" >主机组:</label>
                    <select id='group_id' class="form-control">
                     <option value ="all">未分组</option>
                                     {% for group in request.user.host_groups.select_related %}
                                     <option value ="{{ group.id }}">{{ group.name }}  [ {{ group.bindhosttouser_set.select_related.count }} ]</option>
                                     {% endfor %}
                    </select>
                </div>
                        <div class="form-group">
                              <label class="control-label" for="args">用户:</label>
                              <select id='local_filename' class="form-control" name="local_filename">
                              <option value="odin">odin</option>
                              </select>

                       </div>
               <button id="execute" type="submit" class="btn btn-success" data-toggle="modal" data-target="#restModal">执行命令</button>
               <button id="history" type="submit" class="btn btn-default">历史记录</button>
               <!--  <button type="button"   style="margin-left:50px" id="btn_query" class="btn btn-success pull-right" onclick="SubmitTask()" >执行任务</button> -->
            </div>
        </div>
        <table id = "tb1"
             data-toggle="table"
             data-show-columns="true" 
             data-toolbar="#toolbar" 
             data-search="true" 
             data-show-toggle="true"
             data-pagination="true"
             data-url="/hosts/hosts_list"
             data-reorderable-columns="true">
            <thead>
            <tr>
                  <th data-field="state" data-checkbox="true"></th>
                  <th data-field="id" data-sortable="true">ID</th>
                  <th data-field="hostname" data-sortable="true">Hostname</th>
                  <th data-field="ipaddr" data-sortable="true">IP</th>
                  <th data-field="systemtype" data-sortable="true">System type</th>
            </tr>
            </thead>
        </table>                                                                                                                                                               
    </div>                   
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            <!-- /.row -->

<div class="modal-header">
    <button type="button" class="close" ng-click="$dismiss()">&times;</button>
    <h3 class="modal-title">
        工具执行详情
    </h3>
</div>



<div class="modal fade" id="restModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
                <div class="modal-content">
                        <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                        &times;
                                </button>
                                <h4 class="modal-title" id="myModalLabel"> {{ cmd  }}
                                        模态框（Modal）标题
                                </h4>
                        </div>
                        <div class="modal-body">
                             <div class="row">
                                   <div id="result_data" class="col-sm-6">
                                       <dl class="dl-detail dl-sm">
                                                <dt>结果:</dt>
                                                <dd><span tool-result status="executionResult.totalStatus">{{ result.minion_count }}    {{ result.cmd_succeed }}    {{ cmd_failure }}    {{ failure_minion }}</span></dd>
                                        </dl>
  
                                   </div>
                                   <div id="Failure_data" class="col-sm-6">
                                            <dl class="dl-detail dl-sm">
                                              <dt>用户:</dt>
                                              <dd>{{executionResult.username}}</dd>
                                           </dl>
                                   </div> 
                             </div>
                             <div class="ui-tab">
                                <ul class="nav nav-tabs">
                                  <li ng-repeat="agent in executionResult.agents" ng-class="{active: activeAgent === agent}">
                                   <a href ng-click="setActiveAgent(agent)" >{{agent}}192.168.1.132<i tool-agent-result status="executionResult.status[agent]"></i></a>
                                 </li>
                                </ul>
                               <div class="tab-content">
                                   <div id="exec_output" class="form-group" ng-if="executionResult.outputs[activeAgent]">
                                       <label class="control-label">执行输出</label>
                                       <dl class="tool-outputs">
                                           <dt ng-repeat-start="(key, value) in executionResult.outputs[activeAgent]" ng-bind="key">key</dt>
                                           <dd ng-repeat-end>
                                               <pre ng-bind="value" style="background: #2f333d;color: #c5c8c6" ></pre>
                                           </dd>
                                       </dl>
                                   </div>
                               </div>
                             </div>
                        </div>
                        <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                                </button>
                        </div>
                </div><!-- /.modal-content -->
        </div><!-- /.modal -->
</div>
<script type="text/javascript">                                                                                                                         

     var $table = $('#table'),
         $exec = $('#execute');
     var data_list = {};
     var hostids = '';
     $(function () {
        $exec.click(function () {
          //var row=JSON.stringify($table.bootstrapTable('getSelections'));
          //alert(row);
           var hosts = getIdSelections()
           var hostname = getNameSelections()
           var cmd = $.trim($("textarea[name='cmd']").val());
           if (hosts){
            $.ajax({
	    url: "/hosts/command/", 
	    data: { 
	       host_ip : hosts,
               host_name : hostname,
               cmd_text : cmd
	    }, 
	    type: "POST",
            dataType : "json",
	    cache : false,
	    success: function(data) {
               $('#exec_output').empty();
               //var obj =[{"name":"admin","password":"123456"}];
               //alert(obj)
               dat = data.result
               var html ='',html_F=''; 
               for(i=0;i<dat.length; i++){
                   html += "<dl> <dt>结果 :</dt><dd>"+dat[i]['minion_count'] +' '+ dat[i]['cmd_succeed']+' ' +dat[i]['cmd_failure'] +"</dd>  <dt>目标:</dt> <dd> "+dat[i]['hosts'] +"</dd></dl>";
                   html_F += "<dl> <dt>用户:</dt><dd>odin</dd>  <dt>失败:</dt> <dd> "+dat[i]['failure_minion'] +"</dd></dl>";
                      
                }
                $('#Failure_data').html(html_F)
                $('#result_data').html(html)
               msg = data.msg
               var html = '';
               $.each(msg,function(k,v){
                    html += "<dl> <dt>Minions : "+k+"</dt><dd><pre style='background: #2f333d;color: #c5c8c6'>"+v+"</pre></dd> </dl>";
               });
               //$('.modal-body').append(html);
               $('#exec_output').html(html)
	    },error: function( xhr, status, errorThrown ) {
	    alert( "Sorry, there was a problem!" );
	    console.log( "Error: " + errorThrown );
	    console.log( "Status: " + status );
	    console.dir( xhr );
	    },	    
	    });
           }
        });
    });
    function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
        return row.ip;
    });
    }
    function getNameSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {
        return row.hostname;
    });
    }
   
function getIdSelections() {
    return $.map($table.bootstrapTable('getSelections'), function (row) {                                                                                                      
        return row.ip;
});}
function getNameSelections() {
  return $.map($table.bootstrapTable('getSelections'), function (row) {
     return row.hostname;
});}
var $table = $('#tb1');
$("select#group_id").on("change",function(){
    var data = []
    var $table = $('#tb1');
    var gid = $('select#group_id').val();
    $.ajax({
    url: "/hosts/hosts_list",
    data: {
        selected_gid : gid
    },
    type: "GET",
    dataType : "json", 
    
    success: function(data) {
        //$table.bootstrapTable({data: data});
        $table.bootstrapTable('load', data);
    }, error: function( xhr, status, errorThrown ) {                                                                                                                           
        alert( "Sorry, there was a problem!" );                                                                                                                                
        console.log( "Error: " + errorThrown );                                                                                                                                
        console.log( "Status: " + status );                                                                                                                                    
        console.dir( xhr );                                                                                                                                                    
    },                                                                                                                                                                         
                                                                                                                                                                               
    })                                                                                                                                                                         
});

$('#restModal1').on('show.bs.modal', function (event) {
   $(this).removeData('bs.modal');
   var modal = $(this);
   var hosts = getIdSelections()
   var hostname = getNameSelections()
   var cmd = $.trim($("textarea[name='cmd']").val());
   $.ajax({
            url: "/hosts/command/", 
            data: { 
               host_ip : hosts,
               host_name : hostname,
               cmd_text : cmd
            }, 
            type: "POST",
            //dataType : "json",
            cache : false,
            success: function(data) {
               //window.location.reload();
               alert("====")
            },error: function( xhr, status, errorThrown ) {
            alert( "Sorry, there was a problem!" );
            console.log( "Error: " + errorThrown );
            console.log( "Status: " + status );
            console.dir( xhr );
            },      
            });
  
});


</script> 

        </div>
        <!-- /#page-wrapper -->
{% endblock %}

templates/hosts/cmd_result.html
ll

templates/hosts/dashboard.html
{% extends 'base.html' %}

{% block sidebar %}
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'host_mgr' %}">主机管理</a></li>
        <li><a href="{% url 'multi_cmd' %}">批量命令</a></li>
        <li><a href="{% url 'file_manage' %}">文件分发</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="#">任务计划</a></li>
        <li><a href="#">审计</a></li>
      </ul>
{% endblock %}

{% block content-panel %}
Hosts
{% endblock %}

{% block bottom-js %}
    <script type="text/javascript">

    $(document).ready(function(){
        $("#navbar-menu a[href='"+ "{% url 'hosts' %}"  + "']").parent().addClass("active");

    });

    </script>

{% endblock %}

templates/hosts/file_push.html
{% extends 'index.html' %}
{% block context %}
<form class="form-inline" method="post">
  <div class="form-group">
    <label class="sr-only" for="saltkey">saltkey</label>
    <input type="text" class="form-control" id="saltkey" name="saltkey" placeholder="saltkey">
  </div>
  <div class="form-group">
    <label class="sr-only" for="module_name">remote_dir</label>
    <input type="text" class="form-control" id="remote_dir" name="remote_dir" placeholder="远端文件的目录">
  </div>
  <div class="form-group">
    <label class="sr-only" for="args">local_filename</label>
    <select class="form-control" name="local_filename">
	<option value="file1">file1</option>
	<option value="file2">file2</option>
    </select>
  </div>
  <button type="submit" class="btn btn-default">执行</button>
</form>
<br/>
	<p>主机: 192.168.91.132</p>
	<p>hostname</p>
{% endblock %}

templates/hosts/multi_cmd.html
{% extends 'hosts/dashboard.html' %}

{% block content-panel %}
<div class="col-md-3">

    <div class="panel panel-default panel-left">
        主机组
      <div class="panel-body">
        <ul id="group-list" class="list-group">

          <li class="list-group-item borderless">
            <span class="badge">{{ request.user.bind_hosts.select_related.count }}</span>
            未分组主机
          </li>
          {% for group in  request.user.host_groups.select_related %}
            <li class="list-group-item borderless">
                <input onclick="CheckAllToggle(this)" data="host-group" type="checkbox" value="{{ h.id }}">
                <a  data='group' class="a-pointer">
                    {{ group.name }}
                    <span class="badge">{{ group.bindhosttouser_set.select_related.count }}</span>

                </a>

                <ul class="list-group hide">
                    {% for h in group.bindhosttouser_set.select_related %}
                    <li class="list-group-item list-tree"><span>-- </span><input data="bind-host" type="checkbox" value="{{ h.id }}">{{ h.host.hostname }}</li>
                    {% endfor %}
                </ul>
            </li>
          {% endfor %}
        </ul>

      </div>
    </div>
</div>

<div class="col-md-9">
    <div class="panel panel-default panel-right">
      <div class="panel-body">

          <textarea name="cmd" class="form-control" rows="3" placeholder="输入要执行的命令..."></textarea>
          <br/>
          <button type="button" class="btn btn-success pull-right" onclick="SubmitTask('multi_cmd')">执行命令</button>

          <div id="err-msgs"></div>
      </div>
</div>

        <div class="row">
            </div>
        <div class="row col-lg-12">
            <form class="form-inline" role="form">
                <div class="form-group">
                    <label for="order_no"  class="label-control">申请单：</label>
                                    <select id='order_no' class="form-control">
                                    <option value =""></option>
                                              <option value ="123456">all</option>
                                  </select>
                                </div>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">查看部署日志</button>
            </form>
            dfdfdf

       </div>

{% endblock %}

{% block bottom-js %}
    <script type="text/javascript">
     $("select#order_no").on("change",function(){
      var order_no_v = $('select#order_no').val();
      alert(order_no_v)
     });
     $(document).ready(function(){
         $("#group-list a[data='group']").click(function(){
             $(this).nextAll().toggleClass("hide");

         });//end #group-list li[href='group']"

     });//end doc ready


    function CheckAllToggle(ele){

       if(ele.checked){//把它下面所有的主机都 全选
            $(ele).next().next().children().children("input").prop("checked",true);
       }else{

            $(ele).next().next().children().children("input").prop("checked",false);

       }

    }
    function SubmitTask(task_type){

        if (task_type == 'multi_cmd'){
            FormVerification(task_type);

        }

    }
    function FormVerification(task_type){
        var err_list = [];
        var data_list = {};
        if (task_type == 'multi_cmd'){
            var selected_host = VerifyHostSelection();
            data_list['selected_hosts'] = selected_host;
            var cmd_text = $.trim($("textarea[name='cmd']").val());
            data_list['cmd'] = cmd_text;
            data_list['task_type'] = task_type;

            if (selected_host.length == 0){
                err_list.push(['验证失败',"未选择任何主机!"])
            }
            if (cmd_text.length == 0){
                err_list.push(['验证失败',"未输入要执行的命令!"])
            }
        }


        if (err_list.length>0){
             $("#err-msgs").html(" ");
            $.each(err_list,function(index,item){
                var err_msg = "<p style='color:red;'>" + index + ". " + item[1] + "</p>";
                $("#err-msgs").append(err_msg);
            })

        }else{
             $("#err-msgs").html(" ");
            //提交任务
            data_list["csrfmiddlewaretoken"] = $("input[name='csrfmiddlewaretoken']").val();
            $.post("{% url 'submit_task' %}", data_list, function(callback){
                console.log(callback);
            });//end post

        }
    }

    function VerifyHostSelection(){
        var selected_hosts = [];
        var all_hosts =  $("input[data='bind-host']");
        $.each(all_hosts, function(index,ele){
            if(ele.checked){
                selected_hosts.push($(ele).val());
            }
        });//end each
      return selected_hosts;
    }
    </script>
{% endblock %}